### ISSUE TITLE
Gif video making does not work

### ISSUE THREAD

**Issue by ErikPoppleton** [sulcgroup/oxdna-viewer#9]
If you try to save a video output as gif the following error occurs when it tries to save the file:

`Uncaught DOMException: Failed to construct 'Worker': Script at 'file:///home/erik/Simulations/oxdna-viewer/ts/lib/gif.worker.js' cannot be accessed from origin 'null'.
    at file:///home/erik/Simulations/oxdna-viewer/ts/lib/CCapture.all.min.js:1:18044
    at Array.forEach (<anonymous>)
    at e.spawnWorkers (file:///home/erik/Simulations/oxdna-viewer/ts/lib/CCapture.all.min.js:1:17956)
    at e.render (file:///home/erik/Simulations/oxdna-viewer/ts/lib/CCapture.all.min.js:1:17271)
    at u.save (file:///home/erik/Simulations/oxdna-viewer/ts/lib/CCapture.all.min.js:2:2864)
    at Object.v [as save] (file:///home/erik/Simulations/oxdna-viewer/ts/lib/CCapture.all.min.js:1:28972)
    at HTMLButtonElement._done (file:///home/erik/Simulations/oxdna-viewer/dist/main.js:845:18)`

This problem looks like its on CCapture's end, not ours, but probably worth looking into.

**Comment by Akodiat** [comment]
Hmm, that looks like this issue: https://github.com/spite/ccapture.js/issues/91, so maybe you could try running it from a local server as suggested? But I've never had any problems running it without a server.

**Comment by Akodiat** [comment]
Gif creation works in Chrome only while run from a server, so this is only an issue when running locally.
With Firefox it works fine locally too. On the other hand, the WebM Writer works only in Chrome, as per [CCapture limitations](https://github.com/spite/ccapture.js/#limitations)
